// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NguyenHoangViet0689.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230623012445_Create_Table_NHVstudent")]
    partial class Create_Table_NHVstudent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("NguyenHoangViet0689.Models.NHVstudent", b =>
                {
                    b.Property<int>("NHVMaSV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NHVTenSV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("NHVsdt")
                        .HasColumnType("REAL");

                    b.HasKey("NHVMaSV");

                    b.ToTable("NHVstudent");
                });
#pragma warning restore 612, 618
        }
    }
}
